a=print("Bienvenue sur JUMIO S.A.R.L")
prix_unitaire=float(input("entrez le prix unitaire"))
quantite=float(input("entrez la quantite"))
prix_ht=float(input("entrez le montant ht"))
prix_tva=float(input("entrez le montant tva")) 
prix_ttc=float(input("entrez le montant ttc"))
print("\nVOTRE FACTURE")
print(f"p.u :{prix_unitaire:3000f} CFA")
print(f"quantite :{quantite:3}")
print("montant HT est: , 9000F CFA")
print("TVA est: , 1620f CFA")
print("montant TTC est: , 10620f CFA") 
print("JUMIO vous remercie pour votre achat et vous souhaite de joyeuses fetes!")
